### DISCUSSION TITLE
Reduce NGINX spans

### DISCUSSION THREAD

**Discussion by fede843** [open-telemetry/opentelemetry-cpp-contrib#345] [Q&A]
Hi, I am testing the NGINX module. So far it works as expected.
I am trying to tuneup the traces content, and at the moment I am getting by default more than 10 spans on each request, which is totally fine for the general audience I guess, but I would like to reduce it, maybe to the root span only in my case, from the module configuration if possible. Is there any workaround?

**Comment by fede843** [comment]
For the record, I can just add an otel filter like this 

```
processors:
  filter/nginx:
    traces:
      span:
        - IsMatch(name, "ngx_http.*")
```

and it solves my case. But still, NGINX is using resources to create those spans before the filter applies.
