### ISSUE TITLE
nginx: design question: Why does the sampler default to parent_based=false?

### ISSUE THREAD

**Issue by dgoffredo** [open-telemetry/opentelemetry-cpp-contrib#331]
Hi,

I'm writing an OpenTelemetry [TracerProvider][2] implementation that is a wrapper around [Datadog's tracing library][1]. My intention is to eventually add support for that provider in this project's `instrumentation/nginx` module.

I notice that in the [sampling configuration][3], `sampler.parent_based` [defaults to `false`][4], which means that while nginx will extract trace context from an incoming request, it will by default not honor the sampling decision included in that context. Instead it will make its own sampling decision (which defaults to "always on").

Why was this chosen as the default? In the hypothetical Datadog case, I'd prefer `parent_based` to default to `true`.

@johanneswuerbach, the author of the configurable sampler.

[1]: https://github.com/DataDog/dd-trace-cpp
[2]: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/trace/tracer_provider.h
[3]: https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/26
[4]: https://github.com/open-telemetry/opentelemetry-cpp-contrib/blob/d30eb603d88aed3c33b77a0d4efde4a6ed881407/instrumentation/nginx/src/agent_config.h#L37

**Comment by trajano** [comment]
In my case I found it the other way by default with Java instrumentation which is `parent_based_always_on` which I actually set to `parent_based_always_off` in my service.

The advantage of `parent_based_always_off` is it allows me to drop the whole span if the parent trace is filtered using a `filter` in OpenTelemetry Collector like this

```
  filter/grafana_noise:
    error_mode: ignore
    traces:
      span:
        - (resource.attributes["service.name"] == "grafana") and (attributes["http.url"] == "/grafana/metrics") and (attributes["http.method"] == "GET")
        - (resource.attributes["service.name"] == "grafana") and (name == "open session") and (attributes["transaction"] == false)

  filter/drop_actuator:
    traces:
      span:
        - (attributes["http.method"] != nil) and (attributes["http.method"] == "GET") and (attributes["http.route"] == "/actuator/prometheus")
        - (attributes["http.method"] != nil) and (attributes["http.method"] == "GET") and (attributes["http.route"] == "/actuator/health")
        - (attributes["http.url"] == "/grafana/metrics") and (attributes["http.method"] == "GET")
        - (attributes["http.url"] == "/metrics") and (attributes["http.method"] == "GET")
```

When the traefik span that starts the whole process gets dropped the whole trace itself gets dropped.  Primarily I want to remove the /metrics polling and /health checks
